#YAML:1.0
Imagefile: 00032009.jpg
Contourscount: 8
image_width: 640
image_height: 480
camera_matrix:
   rows: 3
   cols: 3
   dt: d
   data: [ 1118.51449, 0., 348.10129, 0.,
        1120.60939,  195.92066, 0., 0., 1. ]
distortion_coefficients:
   rows: 5
   cols: 1
   dt: d
   data: [ -0.05909, -0.31834, -0.00852, 0.00321, 0.00000 ]